### ISSUE TITLE
Laravel 5.4 , Minimum Stability Issue

### ISSUE THREAD

**Issue by ksathyanarayana** [IGonics/laravel-disqus-sso#1]
Hi,

I'm using Laravel 5.4, I'm unable to install this package. I keep getting minimum stability error. Is this because the current package requires 
"require": {
        "php": ">=5.4.0",
        "illuminate/support": "5.1.*|5.2.*|5.3.*"
    },
these configurations? , Is there a work around?. Can you please help resolve this issue.

![image](https://cloud.githubusercontent.com/assets/22160054/23337697/e866ea12-fbbb-11e6-95a3-dda02ce9a2e5.png)

![image](https://cloud.githubusercontent.com/assets/22160054/23337709/19c3439e-fbbc-11e6-9101-c2d46ae01677.png)

**Comment by gggordon** [comment]
Hi,

I'll test the package with 5.4 before publishing an update.

**Comment by gggordon** [comment]
Package now supports Laravel 5.4

**Comment by rebornishard** [comment]
sorry got some error in 5.4

```
  [InvalidArgumentException]
  Could not find package igonics/disqus-sso at any version for your minimum-s
  tability (stable). Check the package spelling or your minimum-stability
```

**Comment by gggordon** [comment]
Hi @rebornishard , try ``composer require igonics/laravel-disqus-sso``. You may have had a typo 

[Official Packagist Link](https://packagist.org/packages/igonics/laravel-disqus-sso)

**Comment by rebornishard** [comment]
@gggordon it's not just me who typo, see readme.md :)
thanks

**Comment by trollid** [comment]
@gggordon send pull request 👍
